# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(372A2C)
$foreground = rgb(EAE6E4)
$color0 = rgb(5D4F51)
$color1 = rgb(2E3132)
$color2 = rgb(313435)
$color3 = rgb(8D1D38)
$color4 = rgb(5B5957)
$color5 = rgb(625F5C)
$color6 = rgb(928A85)
$color7 = rgb(D8D3D0)
$color8 = rgb(979491)
$color9 = rgb(3D4143)
$color10 = rgb(414546)
$color11 = rgb(BC274B)
$color12 = rgb(797774)
$color13 = rgb(827F7B)
$color14 = rgb(C2B8B1)
$color15 = rgb(D8D3D0)
