# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(120E16)
$foreground = rgb(F9F8FB)
$color0 = rgb(1E172B)
$color1 = rgb(543798)
$color2 = rgb(241A30)
$color3 = rgb(322A58)
$color4 = rgb(9881A3)
$color5 = rgb(543798)
$color6 = rgb(F9F8FB)
$color7 = rgb(F9F8FB)
$color8 = rgb(9881A3)
$color9 = rgb(322A58)
$color10 = rgb(543798)
$color11 = rgb(9771B2)
$color12 = rgb(F9F8FB)
$color13 = rgb(F9F8FB)
$color14 = rgb(F9F8FB)
$color15 = rgb(FFFFFF)
