# Nombres personalizados para dispositivos de audio
# Formato: descripcion_exacta=nombre_custom
# Podés ver las descripciones exactas corriendo: pactl list sinks | grep Description

[G533 Wireless Headset Dongle] Analog Stereo=G533 Headset
Navi 21/23 HDMI/DP Audio Controller Digital Stereo (HDMI 5)=Monitor HDMI
Starship/Matisse HD Audio Controller Digital Stereo (IEC958)=Placa de sonido
