# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# Commands and Apps to be executed at launch

exec-once = REPLAY_OUTPUT_DIR=/mnt/1tb/Clips REPLAY_MONITOR=DP-2 REPLAY_QUALITY=18000 replay-clip autostart
